<a href="https://colab.research.google.com/github/rdnrubens97/Machine_Learning/blob/main/Matriz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [6]:
matriz = np.array([[2, 3, 1], 
                   [4, 5, 7]])

In [7]:
matriz

array([[2, 3, 1],
       [4, 5, 7]])

In [8]:
matriz.shape

(2, 3)

In [9]:
print(matriz[0])
print(matriz[1])
print(matriz[0, 0])

[2 3 1]
[4 5 7]
2


In [10]:
soma = 0
for i in range(matriz.shape[0]):
  for j in range(matriz.shape[1]):
      soma = soma + matriz[i][j]
print(soma)      

22
