<a href="https://colab.research.google.com/github/rdnrubens97/Machine_Learning/blob/main/Matriz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
matriz = np.array([[2, 3, 1], 
                   [4, 5, 7]])

In [4]:
matriz

array([[2, 3, 1],
       [4, 5, 7]])

In [5]:
matriz.shape

(2, 3)

In [13]:
print(matriz[0])
print(matriz[1])
print(matriz[0, 0])

[2 3 1]
[4 5 7]
2


In [16]:
for i in range(matriz.shape[0]):
  print(matriz[i])  
  for j in range(matriz.shape[1]):
    print(matriz[i, j])

[2 3 1]
2
3
1
[4 5 7]
4
5
7
